### ISSUE TITLE
Error when including relative path

### ISSUE THREAD

**Issue by 8dcc** [nrootconauto/HolyCC2#10]
After compiling `hcc` in `HolyCC2/build/`, I tried the following:

```console
$ ./hcc ../tests/fuzzTest.c
...
/home/username/HolyCC2/build/../tests/fuzzTest.c:1,1: error: Couldn't find file "/home/username/HolyCC2/build/../tests/fuzzTest.c../IR2asm.h" for include.

#include "../IR2asm.h"
#include "../cleanup.h"
```

The included filename should be appended to the *directory* of the source, not to the *path* of the source:

```bash
/home/username/HolyCC2/build/../tests/fuzzTest.c../IR2asm.h  # Bad
/home/username/HolyCC2/build/../tests/../IR2asm.h            # Good
```

**Comment by 1fishe2fishe** [comment]
I might have been a bit late but HolyCC was more or less a non-functional pre-alpha compiler. You should use [Aiwnios](https://github.com/nrootconauto/Aiwnios) or [Exodus](https://github.com/1fishe2fishe/EXODUS) for a proper port of the HolyC compiler to user space.

**Comment by 8dcc** [comment]
> I might have been a bit late but HolyCC was more or less a non-functional pre-alpha compiler. You should use [Aiwnios](https://github.com/nrootconauto/Aiwnios) or [Exodus](https://github.com/1fishe2fishe/EXODUS) for a proper port of the HolyC compiler to user space.

Thank you for the reply, but I am a bit confused. Are those HolyC compilers, or TempleOS forks? I was looking for a tool that could compile HolyC code into an x86/x86_64 ELF binary, for example.

**Comment by 1fishe2fishe** [comment]
HolyC is just C89 with some additions in a language perspective, but there's a command line option in both of the projects I have mentioned that allows you to run HolyC as a script by invoking them with `-c filename.HC`. They are "TempleOS running in userland" - you can run HolyC just like it's in TempleOS without a VM.

The whole point of HolyC is that it's JIT'ed, and that you don't need to compile them into a separate executable file. Also all of the "true" HolyC compilers ([the most active one being this](https://github.com/Jamesbarford/holyc-lang)) that compile HolyC into executables only seem to have ported over printf and basic class definitions, I don't think you can go much further than a hello world with them let alone run any of what stock TempleOS supplies you with.
